---
title: "R Notebook"
output: html_notebook
---

#load relevant libraries and import data
```{r}
#install and load the relevant libraries(packages)
install.packages("pacman")
library("pacman")
p_load( "tidyverse", "stringr", "ggtext", "ggplot2", "ggrepel", "readr", "dplyr", "here")
 tt <- read_tsv("https://zenodo.org/record/2529117/files/limma-voom_luminalpregnant-luminallactate"
         )
```

```{r}
#prepare your working directory(a directory into which all your progress gets stored)
here()
setwd(here())
```

#exploration of dataset
```{r}
head(tt)
colnames(tt)

```
#add a new column to tag genes as deg 
```{r}
tt$deg <- "NO"
unique(tt$deg)

#regulated genes
tt$deg[tt$logFC > 0.58 & tt$adj.P.Val <0.01] <- "UP"

tt$deg[tt$logFC < -0.58 & tt$adj.P.Val < 0.01] <- "DOWN"

head(tt$deg)
unique(tt$deg)

#create new column 
tt$delabel <- NA

```
#
```{r}
#fill up delabel column with genes symbols of genes with the most significant expression levels(top 10 P.Values)
#annotates the plot



head(arrange(tt, P.Value), 10)$P.Value
thres <- head(arrange(tt, P.Value), 10)$P.Value[10]
thres
head(arrange(tt, P.Value))

tt$delabel[tt$P.Value <= thres] <- tt$SYMBOL[tt$P.Value <= thres]


```


##Generate a volcano plot
```{r}
gplot(tt, aes(x = logFC, y = -log10(P.Value),col = deg)) +geom_point()+
  theme_minimal()+
  geom_text_repel(aes(label = delabel))+
  scale_colour_manual(values = c( "blue", "black", "red"), name = "DEG", breaks = c("DOWN", "NO", "UP"), labels = c("Down", "No", "Up") )+
  labs(title=stringr::str_wrap(paste0("A volcano plot displaying the proportion of ", "<span style='color:blue '>**down**</span>", " <br> and "  ,"<span style='color: red '>**up**</span>", " regulated genes in a biological condition"), width = 1))+
  theme( text = element_text(size = 12), panel.grid = element_blank(), axis.line.x = element_line(colour = "black", linewidth = .5), axis.line.y = element_line( colour = "black" ,linewidth = 0.5 ), plot.title= element_markdown(margin = margin(0.5,5,7,5))  , axis.ticks = element_line(linetype = 2), legend.text=element_text(size = 12)) +xlim(c(-10, 10)) + geom_hline( yintercept = -log10(0.001), linetype = 2) 
                     
                      
```



```{r}
#save your Volcano plot
ggsave("Volcano_DEG", plot = last_plot(), device = "pdf", dpi = "retina")
```


```{r}

```












































